from retrieval import search_similar_chunks
from groq_client import generate_response


DIFFICULTY_INSTRUCTIONS = {
    "easy": """
Ask a beginner-friendly question that tests whether the candidate
understands their own project's basic functionality and implementation.
Focus on one file, function, component, or simple technical decision.
""",

    "medium": """
Ask an intermediate question that tests how and why the candidate's
implementation works.

Focus on data flow, interactions between components, implementation
decisions, error handling, or technical trade-offs.
""",

    "hard": """
Ask a difficult question that tests deep technical understanding.

Focus on architecture, scalability, performance, security, reliability,
failure scenarios, trade-offs, refactoring, or extending the system.

The question must still be grounded in the candidate's actual repository.
"""
}


def generate_question(difficulty, history=None):
    if difficulty not in DIFFICULTY_INSTRUCTIONS:
        raise ValueError("Difficulty must be easy, medium, or hard.")

    if history is None:
        history = []

    retrieval_query = (
        f"Find important technical implementation details in this repository "
        f"that would be suitable for a {difficulty} technical interview."
    )

    results = search_similar_chunks(retrieval_query, limit=6)

    context = "\n\n".join(
        f"File: {result['source']}\n"
        f"Language: {result['language']}\n"
        f"Code:\n{result['content']}"
        for result in results
    )

    previous_questions = "\n".join(
        f"Question {i + 1}: {item['question']}\n"
        f"Candidate answer: {item['answer']}"
        for i, item in enumerate(history)
    )

    prompt = f"""
You are a skilled human technical interviewer conducting a one-on-one
interview with a software developer about their own GitHub project.

You are sitting across from the candidate.

Your job is NOT to interrogate the candidate with a list of questions.
Have a natural technical conversation.

DIFFICULTY:
{difficulty}

REPOSITORY CONTEXT:
{context}

PREVIOUS CONVERSATION:
{previous_questions if previous_questions else "This is the beginning of the interview."}

Generate the NEXT thing the interviewer should say.

INTERVIEWER BEHAVIOR:

- Speak naturally and conversationally.
- Sound like an experienced human interviewer.
- Be curious about the candidate's implementation.
- Ask about the candidate's actual project.
- Build naturally on previous answers when appropriate.
- If an answer reveals an interesting design decision, explore it.
- Do not abruptly jump between unrelated topics.
- Do not sound like a quiz or examination.
- Do not say "Question 2", "Question 3", etc.
- Do not say "Based on the provided context".
- Do not mention the repository context or AI.
- Do not give feedback or a score.
- Do not reveal whether the previous answer was correct.
- Do not provide the answer yourself.
- Ask only ONE question.
- Keep the conversational introduction short.
- The question itself should be clear and technically meaningful.

For the first question, you may use a natural opening such as:
"Alright, let's start with..."
"Okay, I'd like to begin by..."
"Let's start with something about..."

For later questions, naturally connect to the previous answer when appropriate.

IMPORTANT:
The candidate should feel like they are talking to a real interviewer,
not reading questions generated by a chatbot.

Return ONLY what the interviewer should say.
"""
    return generate_response(prompt).strip()